[package]
name = "ys-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ys-core = { path = "../ys-core" }
ys-event = { path = "../ys-event" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
