[package]
name = "agent-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
agent-core = { path = "../agent-core" }
agent-event = { path = "../agent-event" }
agent-tool = { path = "../agent-tool" }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
serde_json = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
